import pandas as pd
Car = pd.read_csv('./assets/file (1).csv')
#print(Car.head)
#print(Car.index)
#print(Car.isnull().sum())
#print(Car['Cylinders'].fillna(Car['Cylinders'].mean( ),inplace= True))
#print(Car.isnull().sum())
#print(Car.head(2))
#print(Car['Make'].value_counts())
#print(Car[Car['Origin'].isin(['Asia','Europe'])])
# print(Car.head(2))
#print(Car[Car['Weight']>4000]) 
#print(Car[~(Car['Weight']>4000)])
print(Car.head(2))
#Car['MPG_City'] = Car['MPG_City'].apply(lambda x : x+3)  
#print(Car.head(2)