import pandas as pd
data = pd.read_csv('./file.csv')
#print(data.head())
#print(data.shape)
#print(data.index)
#print(data.columns)
#print(data.dtypes)
#print(data.nunique())
#print(data['Weather'].unique())
#print(data.count())
#print(data['Weather'].value_counts())
#print(data.info())
#print(data['Wind Speed_km/h'].unique())
#print(data['Weather'].value_counts())
#print(data.groupby('Weather').get_group("Clear"))
#print(data.groupby('Wind Speed_km/h').get_group(4))
#print(data['Wind Speed_km/h'].value_counts())
#print(data.isnull().sum())
#print(data.rename(columns= {'Weather' :'Weather Condition '}))
#print(data.Visibility_km.mean())
#print(data.Press_kPa.std())
#print(data['Weather'].value_counts())
#print(data[data['Weather'].str.contains('Snow')])
#print(data['Wind Speed_km/h']> 24) and (data['Visibility_km']==25)
#print(data.groupby('Weather Condition').mean())